import { Dimensions, Platform, StyleSheet } from 'react-native';
import appColors from '../../Themes/colors';
const height = Dimensions.get('screen').height;
const width = Dimensions.get('screen').width;

export const styles = StyleSheet.create({
  headerView: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 30,
    padding: 30,
    backgroundColor: appColors.white,
  },
  drawerAndCircleView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainView: {
    backgroundColor: appColors.appBackgroundColor,
    flex: 1,
    zIndex: -999999,
  },
  contentContainerStyle: {
    flexGrow: 1,
    padding: 20,
  },
  container: {
    // Add shadow styles based on the platform
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 2,
      },
      android: {
        elevation: 2,
      },
    }),
    // Other styles for your component
    backgroundColor: appColors.white,
    borderRadius: 10,
    marginTop: 10,
    alignSelf: 'center',
    marginVertical: 10,
    marginHorizontal: 5.5,
    minHeight: height * 0.23,
    // marginBottom: 100,
  },
  greenView: {
    paddingLeft: 12,
    paddingTop: 5,
    paddingBottom: 10,
    borderTopStartRadius: 10,
    borderTopEndRadius: 10,
  },
  greenViewParticular: {
    paddingLeft: 5,
    paddingTop: 5,
    paddingBottom: 12,
    borderTopStartRadius: 10,
    borderTopEndRadius: 10,
    backgroundColor: appColors.green,
    marginHorizontal: 26,
  },

  tick: {
    width: 23,
    height: 23,
    resizeMode: 'contain',
    marginRight: 10,
  },
  tickParticular: {
    width: 23,
    height: 23,
    resizeMode: 'contain',
    marginTop: 5,
  },
  ring: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
    marginRight: 10,
    marginBottom: 4,
    alignSelf: 'center',
  },
  ringParticular: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  ring2: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
    alignSelf: 'center',
    position: 'absolute',
    right: 12,
  },
  tickAndText: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  name: {
    fontSize: 16,
    color: appColors.white,
    fontWeight: '500',
    marginRight: 10,
  },
  id: {
    fontSize: 14,
    color: appColors.white,
  },
  temp: {
    alignSelf: 'center',
    fontSize: 14,
    fontWeight: '400',
    color: appColors.grey,
  },
  tempValue: {
    alignSelf: 'center',
    fontWeight: '700',
    marginTop: 4,
  },
  minAndMaxView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  textMinAndMax: {
    fontSize: 15,
    fontWeight: '500',
    color: appColors.black,
  },

  stopIcon: {
    height: 20,
    width: 20,
  },
  stopIconButton: {
    backgroundColor: appColors.redBackGRound,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    borderRadius: 5,
    alignSelf: 'center',
    marginTop: 6,
    marginBottom: 6,
  },
  centeredView: {
    width: width,
    flex: 1,
    justifyContent: 'center',
    padding: 25,
    alignSelf: 'center',
    backgroundColor: appColors.lightWhite,
  },
  circleExclation: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    backgroundColor: appColors.white,
  },
  exclamationIcon: {
    fontSize: 16,
    fontWeight: '900',
  },
  stop: {
    color: appColors.white,
    fontSize: 13,
    fontWeight: 'bold',
  },
  crossImage: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  descriptionAndCross: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  descriptionView: {
    backgroundColor: appColors.white,
    padding: 20,
    borderRadius: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 8, // Required for Android
  },
  description: {
    color: appColors.black,
    fontSize: 15,
    fontWeight: '500',
  },
  ok: {
    color: appColors.white,
    fontSize: 18,
    fontWeight: '600',
  },
  buttonOK: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: appColors.appBlueColor,
    borderRadius: 10,
    padding: 10,
    marginTop: 5,
    alignSelf: 'center',
    paddingHorizontal: 40,
  },
  dropdownAndSearchBar: {
    // marginLeft: 21,
    // marginRight: 19,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
  },
  errorText: {
    fontSize: 12,
    color: appColors.error,
    alignSelf: 'center',
    marginHorizontal: 5,
    fontWeight: 'bold',
  },
  lastUpdate: {
    fontSize: 12,
    color: 'rgba(0, 0, 0, 0.54)',
    alignSelf: 'center',
    marginHorizontal: 5,
  },
  lastUpdateParticular: {
    fontSize: 14,
    color: 'rgba(0, 0, 0, 0.54)',
    alignSelf: 'center',
    fontWeight: '600',
    marginTop: 10,
    marginBottom: 30,
  },
  alarmIcon: {
    alignSelf: 'center',
    height: 48,
    width: 48,
    animationName: 'blinker',
    animationDuration: 200,
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
  },
  '@keyframes blinker': {
    from: { opacity: 1 },
    to: { opacity: 0 },
  },
  icon: {
    alignSelf: 'center',
    height: '48px',
    width: '48px',
  },
  centeredView2: {
    width: width,
    height: height,
    position: 'absolute',
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 22.5,
    backgroundColor: appColors.lightWhite,
  },
  blueView: {
    backgroundColor: appColors.white,
    width: '100%',
    borderRadius: 6,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    zIndex: 10,
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 10,
  },
  confirmation: {
    fontSize: 16,
    fontWeight: '500',
    color: appColors.yellow,
    marginVertical: 18,
    marginLeft: 18,
  },
  lineView: {
    width: '100%',
    height: 1,
  },
  areYouSure: {
    marginVertical: 8,
    marginLeft: 18,
    fontSize: 18,
    fontWeight: '700',
    color: appColors.appBlueColor,
    marginTop: 20,
  },
  areYouSure1: {
    marginVertical: 8,
    marginLeft: 18,
    fontSize: 14,
    fontWeight: '500',
    color: appColors.appBlueColor,
  },
  yesAndNoView: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    zIndex: 10,
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 10,
  },
  yesAndNo: {
    fontSize: 14,
    fontWeight: '500',
    color: appColors.white,
  },
  heightView: {
    width: 1.5,
    height: 56,
    backgroundColor: appColors.lightGreen,
  },
  yesAndNo: {
    fontSize: 14,
    fontWeight: '500',
    color: appColors.white,
  },
  ringTickAndText: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  idAndName: {
    marginLeft: 10,
  },
  Id: {
    marginTop: 4,
    color: appColors.white,
    fontSize: 14,
  },
  nameParticular: {
    // fontSize: 20,
    // color: appColors.white,
    // fontWeight: '600',

    fontSize: 16,
    color: appColors.white,
    fontWeight: '500',
    marginRight: 10,
  },
  whiteView: {
    backgroundColor: appColors.white,
    borderBottomStartRadius: 10,
    borderBottomEndRadius: 10,
    marginHorizontal: 26,
  },
  heartbeat: {
    fontSize: 24,
    fontWeight: '500',
    color: appColors.black,
  },
  mainParticular: {
    flex: 1,
    marginVertical: 10,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 2,
      },
      android: {
        elevation: 2,
      },
    }),
    // Other styles for your component
  },
  containerThreeRows: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 20,
    paddingVertical: 5,
  },
  cell: {
    padding: 10,
    borderWidth: 1,
    borderColor: 'gray',
  },
  middleText: {
    fontSize: 18,
    fontWeight: '700',
    color: appColors.black,
    marginLeft: 8,
  },
  particleSize: {
    color: appColors.grey,
    fontSize: 16,
    fontWeight: '500',
  },
  rangeMaxVell: {
    color: appColors.black,
    fontWeight: '700',
    fontSize: 12,
  },
  particularTextView: {
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 90,
  },
  ringAndTickParticular: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  dropDown: {
    width: 14,
    height: 14,
    marginLeft: 22,
  },
  dropDownButton: {
    backgroundColor: appColors.appBlueColor,
    padding: 17,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 10,
    width: '40%',
  },
  alltext: {
    fontSize: 16,
    color: appColors.white,
  },
  pickerContainer: {
    backgroundColor: 'white',
    padding: 16,
  },
  modal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  yesAndNoButtton: {
    backgroundColor: appColors.white,
    justifyContent: 'center',
    alignSelf: 'center',
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 8,
    alignSelf: 'center',
    margin: 5,
  },
  pickerView: {
    width: '40%',
    backgroundColor: appColors.appBlueColor,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export const pickerSelectStyles = StyleSheet.create({
  inputIOS: {
    fontSize: 16,
    padding: 14,
    borderRadius: 4,
    color: appColors.white,
    paddingRight: 30,
    alignSelf: 'center',
  },
  inputAndroid: {
    fontSize: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 8,
    color: 'white',
    paddingRight: 30,
  },
  iconContainer: {
    top: 16,
    right: 16,
  },
});
