const AppConstant = {
  searchSensor: 'Search Sensor...',
  digitracker: 'DIGITRACKER',
  play: 'Play',
  pause: 'Pause',
  temp: 'Temperature (°C) ',
  min: 'Min:',
  max: 'Max:',
  lastUpdate: 'Last Update: ',
  sensors: 'Sensors',
  name: 'Name:',
  id: 'ID:',
  location: 'Location:',
  rangeMin: 'Range Min:',
  rangeMix: 'Range Max:',
  onHold: 'on Hold:',
  on: 'On:',
  off: 'Off:',
  onHold: 'On Hold',
  OffHold: 'Off Hold',
  alarm: 'Alarm',
  notifications: 'Notifications',
  eorgePieterson: 'George Pieterson',
  emigoKiaren: 'Emigo Kiaren',
  georgePieterson: 'George Pieterson',
  loremIpsum: 'Lorem Ipsum',
  michaelJordan: 'Michael Jordan',
  mayorKelly: 'Mayor Kelly ',
  descriptionFirstNotifcation: `s simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
  alerts: 'Alerts',
  health: 'HEALTH',
  care: ' CARE',
  solutions: 'SOLUTIONS',
  loginAccount: 'Login to your account',
  enterYourEmail: 'Enter your Email Id',
  enterPass: 'Enter Password',
  rememberMe: 'Remember me',
  login: 'Login in',
  byContinue: 'By continuing, you agree to our',
  termsOfSerVices: 'Terms of Service',
  privacyPolicy: 'Privacy Policy',
  contentPolicies: 'Content Policies',
  Maxartik: 'Maxartik',
  balance: 'Balance: $100.00',
  myProfile: 'My Profile',
  accountSetting: 'Account Settings',
  logout: 'Logout',
  stopAlarm: 'Stop Alarm',
  ok: 'OK',
  description: 'Description',
  typeSomethingHere: 'Type something here...',
  all: 'All',
  confirmation: 'Confirmation',
  areYouSure: 'Are you sure, please confirm ?',
  yes: 'YES',
  no: 'NO',
  REACT_APP_AMPLIFY_USER_POOL_ID: 'us-east-2_Ro4GMVZwK',
  REACT_APP_AMPLIFY_REGION: 'us-east-2',
  REACT_APP_AMPLIFY_IDENTITY_POOL_ID:
    'us-east-2:e652e8ec-4270-4d57-8591-6d404fb3034b',
  REACT_APP_AMPLIFY_USER_POOL_WEBCLIENTID: '3h7gpop44c2ia0avcuq99g7d58',
  invalidEmailAddress: 'Please enter valid email address.',
  pleaseEnterPass: 'Please enter password.',
  pleaseEnterEmail: 'Please enter email address.',
  sensorOnHold: 'This sensor is on hold, the escalations are off',
  noActiveAlarm: 'No active alarm',
  timeOutActiveAlarm: 'Alarm of type timeout active, some action is needed!',
  outRangeActiveAlarm: 'Alarm of type outRange active, some action is needed!',
};

export default AppConstant;
