const AppImages = {
  drawer: require('../Assets/Images/Vector.png'),
  profile: require('../Assets/Images/profile.png'),
  brandIcon: require('../Assets/Images/logo.png'),
  adminIcon: require('../Assets/Images/Admin.png'),
  activeAdminIcon: require('../Assets/Images/Admin-Active.png'),
  alarmIcon: require('../Assets/Images/Alarm.png'),
  activeAlarm: require('../Assets/Images/Active-icon/Alarm.png'),
  analyticsIcon: require('../Assets/Images/Analytics.png'),
  activeAnalytics: require('../Assets/Images/Analytics-Active.png'),
  blueAlarm: require('../Assets/Images/Alarm-Active.png'),
  clients: require('../Assets/Images/Clients.png'),
  activeClients: require('../Assets/Images/Active-icon/Clients.png'),
  dashBoard: require('../Assets/Images/Dashboard.png'),
  activeDashboard: require('../Assets/Images/Dashboard-Active.png'),
  floorPlan: require('../Assets/Images/Floorplan.png'),
  activeFloorPlan: require('../Assets/Images/Floorplan-Active.png'),
  notifications: require('../Assets/Images/notifications.png'),
  activeNotification: require('../Assets/Images/Active-icon/Notifications.png'),
  particularCate: require('../Assets/Images/Particle.png'),
  activeParticularCate: require('../Assets/Images/Particle-Active.png'),
  report: require('../Assets/Images/report.png'),
  activeReport: require('../Assets/Images/Active-icon/Report.png'),
  sensors: require('../Assets/Images/Sensors.png'),
  activeSensors: require('../Assets/Images/Sensors-Active.png'),
  alerts: require('../Assets/Images/alerts.png'),
  activeAlerts: require('../Assets/Images/Active-icon/Alerts.png'),
  tick: require('../Assets/Images/whiteTick.png'),
  stopIcon: require('../Assets/Images/stop.png'),
  ring: require('../Assets/Images/ring.png'),
  groupProfile: require('../Assets/Images/groupProfile.png'),
  playButton: require('../Assets/Images/play.png'),
  pauseButton: require('../Assets/Images/pause.png'),
  email: require('../Assets/Images/email.png'),
  eye: require('../Assets/Images/openEye.png'),
  closedEye: require('../Assets/Images/closeEye.png'),
  lock: require('../Assets/Images/lock.png'),
  check: require('../Assets/Images/check.png'),
  profileIcon: require('../Assets/Images/profileIcon.png'),
  crossImage: require('../Assets/Images/cross.png'),
  dropdownIcon: require('../Assets/Images/dropdownIcon.png'),
  search: require('../Assets/Images/search.png'),
  batteryAlert: require('../Assets/Images/batteryAlert.png'),
  wifiOffIcon: require('../Assets/Images/wifiOffIcon.png'),
  errorIcon: require('../Assets/Images/errorIcon.png'),
};

export default AppImages;
